spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloblog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.mayblackcat.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml


#日志配置
logging:
  level:
    com.mayblackcat: debug
    org.springframework: warn

server:
  port: 7777

